# SELECT
#     # p.PRODUCT_ID,
#     p.PRODUCT_CODE,
#     # p.PRICE,
#     # SUM(os.SALES_AMOUNT),
#     p.PRICE * SUM(os.SALES_AMOUNT) AS SALES
# FROM OFFLINE_SALE os
# JOIN PRODUCT p ON os.PRODUCT_ID = p.PRODUCT_ID
# GROUP BY p.PRODUCT_ID
# ORDER BY SALES DESC, p.PRODUCT_ID ASC;
SELECT
    PRODUCT.PRODUCT_CODE,
    # PRODUCT.PRICE,
    # SUM(SALES_AMOUNT),
    PRODUCT.PRICE * SUM(SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE
JOIN PRODUCT ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT.PRODUCT_CODE ASC;