WITH NOVEMBER_RENTAL AS (SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
                        GROUP BY CAR_ID),
    MONTH_DISCOUNT AS (SELECT CAR_TYPE, DISCOUNT_RATE
                      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                      WHERE DURATION_TYPE = '30일 이상')
SELECT
    c.CAR_ID,
    c.CAR_TYPE,
    FLOOR(c.DAILY_FEE * 30 * ((100 - d.DISCOUNT_RATE) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN MONTH_DISCOUNT d ON c.CAR_TYPE = d.CAR_TYPE
WHERE (c.CAR_TYPE = '세단' OR c.CAR_TYPE = 'SUV')
AND c.CAR_ID NOT IN (SELECT CAR_ID FROM NOVEMBER_RENTAL)
AND FLOOR(c.DAILY_FEE * 30 * (100 - d.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC;