SELECT
    a.APNT_NO,
    p.PT_NAME,
    p.PT_NO,
    d.MCDP_CD,
    d.DR_NAME,
    a.APNT_YMD
FROM APPOINTMENT a
JOIN PATIENT p ON p.PT_NO = a.PT_NO
JOIN DOCTOR d ON d.DR_ID = a.MDDR_ID
WHERE
d.MCDP_CD = 'CS'
AND YEAR(APNT_YMD) = 2022
AND MONTH(APNT_YMD) = 4
AND DAY(APNT_YMD) = 13
AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC;