SELECT
    YEAR(DIFFERENTIATION_DATE) AS 'YEAR',
    sq.MAX - ed.SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA ed
JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS 'YEAR',
        MAX(SIZE_OF_COLONY) AS 'MAX'
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) sq
ON YEAR(ed.DIFFERENTIATION_DATE) = sq.YEAR
ORDER BY YEAR ASC,
YEAR_DEV ASC;