SELECT
    c.CAR_ID
    # c.CAR_TYPE,
    # h.HISTORY_ID,
    # h.START_DATE,
    # h.END_DATE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
WHERE c.CAR_TYPE = '세단'
AND MONTH(h.START_DATE) = 10
GROUP BY c.CAR_ID
# HAVING
ORDER BY c.CAR_ID DESC;