# SELECT
#     g.SCORE,
#     g.EMP_NO,
#     e.EMP_NAME,
#     e.POSITION,
#     e.EMAIL
# FROM HR_GRADE g
# JOIN HR_EMPLOYEES e ON g.EMP_NO = e.EMP_NO
# # JOIN HR_DEPARTMENT d ON e.DEPT_ID = d.DEPT_ID
# WHERE SCORE = (SELECT
#                 MAX(SCORE)
#                 FROM HR_GRADE)
SELECT
    SUM(SCORE) AS SCORE,
    e.EMP_NO,
    e.EMP_NAME,
    e.POSITION,
    e.EMAIL
FROM HR_GRADE g
JOIN HR_EMPLOYEES e ON g.EMP_NO = e.EMP_NO
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;