WITH CODES AS (SELECT
               SUM(`CODE`) AS CODE_SUM,
               CATEGORY
               FROM SKILLCODES
               GROUP BY CATEGORY)
SELECT
    CASE
        WHEN SKILL_CODE & (SELECT CODE_SUM FROM CODES WHERE CATEGORY = 'Front End')
        AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0 THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0 THEN 'B'
        WHEN SKILL_CODE & (SELECT CODE_SUM FROM CODES WHERE CATEGORY = 'Front End') THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS
WHERE SKILL_CODE & ((SELECT CODE_SUM FROM CODES WHERE CATEGORY = 'Front End') 
                    + (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0
ORDER BY GRADE ASC, ID ASC